### ISSUE TITLE
The order of elements in a go struct varies from the order in xsd

### ISSUE THREAD

**Issue by akankaria** [metaleap/go-xsd#23] opened 2016-02-26 06:21 UTC
Hi,

First of all this is a wonderful package which reduced my task significantly. So kudos for that.

Secondly, I am trying to use the go-xsd package to convert a xsd file to go schema. 
As my xsd uses xs:Sequence tag, I want the xsd order to be maintained in go struct.
The order of attributes of the go structs which are generated differ from the order specified in xsd. Moreover, the order of attributes of go struct is different every time.

This results in an incorrect order of attribute tags in xml request while serialization of go struct. 

Please let me know if you already have a functionality to maintain the xsd order (by using some flag) or you plan to include this.

Thanks,
Ashish

**Comment by psywolf** [comment] 2016-03-28 04:48
This looks like a duplicate of issue #7 ?

**Closed** 2017-02-12 02:08 UTC
